[package]
name = "wordperms"
version = "0.2.0"
edition = "2024"
description = "generate word permutations"
licence = "MIT"
authors = ["Attila Repka"]


[package.metadata.deb]
revision = ""

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
rayon = "1.11.0"
